apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::933367720501:role/service-role/codebuild-brain-tasks-build-service-role
      username: codebuild
      groups:
        - system:masters
