version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: brain-tasks-app
    AWS_DEFAULT_REGION: us-east-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 
        | docker login --username AWS --password-stdin 933367720501.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 933367720501.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push 933367720501.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
      - echo Deploying to EKS...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
