version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: brain-tasks-app
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    commands:
      - echo "Starting install phase..."
      - yum install -y unzip || true

  pre_build:
    commands:
      - echo "Installing AWS CLI v2..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - aws --version
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 933367720501.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 933367720501.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo "Pushing image..."
      - docker push 933367720501.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
